version: '3.9'

services:
  builder:
    image: archlinux:latest
    container_name: arch_pkg_builder
    tty: true
    stdin_open: true
    working_dir: /home/builder/pkgbuild
    command: |
      /bin/bash -c "
      pacman -Sy --noconfirm git base-devel sudo python &&
      useradd -m builder &&
      echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
      mkdir -p /home/builder/pkgbuild &&
      chown builder:builder /home/builder/pkgbuild &&
      sudo -u builder git clone https://github.com/livcl-be/vscode-projects-launcher /home/builder/pkgbuild &&
      cd /home/builder/pkgbuild &&
      sudo -u builder makepkg -si --noconfirm
      "
