[[projects]]
name = "Project 1"
location = "/home/user/src/cast"
profile = "CAST"

[[projects]]
name = "Project 2"
location = "/home/user/src/side"
profile = "Default"

[[projects]]
name = "Project 3"
location = "/home/user/src/cast"
profile = "Webdev"

[[projects]]
name = "Project 4"
location = "/home/user/src/side"
profile = "Platformio"

[[projects]]
name = "Project 5"
location = "/home/user/src/cast"
profile = "cpp"

[[projects]]
name = "Project 6"
location = "/home/user/src/side"
profile = "Default"