[[projects]]
name = "CAST (= Component Assembly Storage Tracker )"
location = "/home/flippedlama/shared/src/CAST"
profile = "webdev"

[[projects]]
name = "Bloesems in September"
location = "/home/flippedlama/shared/src/bloesems-in-september"
profile = "webdev"

[[projects]]
name = "Raycaster in Zig"
location = "/home/flippedlama/shared/src/raycaster-in-zig"
profile = "Default"

[[projects]]
name = "Draai OS"
location = "/home/flippedlama/shared/src/draaios"
profile = "DraaiOS"